# Generated by Django 3.0.3 on 2020-02-09 04:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datademo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='custom_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
